### ISSUE TITLE
Hostile Mobs

### ISSUE THREAD

**Issue by Legit4K** [Nukkit-coders/MobPlugin#102]
Unfortunately hostile mobs do not spawn, at all, during the night, or even day. However they spawn in the nether, none in overworld though.

**Comment by PetteriM1** [comment]
I'm unable to confirm that. Please use the issue template to provide all needed information.

**Comment by Legit4K** [comment]
Edited issue description

**Comment by Legit4K** [comment]
Fixed by properly setting the time in server
