### ISSUE TITLE
Server random stops responding

### ISSUE THREAD

**Issue by KnifeDev** [Nukkit-coders/MobPlugin#103]
I have a last-version plugin.
Server random stops responding and crashed.
Error (Stack trace): https://pastebin.com/eXnkbGhH 
My config.yml: https://pastebin.com/SdDu8n6t
I don’t know anything else about this error.

**Comment by PetteriM1** [comment]
Does this still happen in version 1.8.0.1?

**Comment by PetteriM1** [comment]
Closed until someone can confirm this still happnes
