### ISSUE TITLE
All player got disconnected

### ISSUE THREAD

**Issue by MrReskill** [Nukkit-coders/MobPlugin#126]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

sometimes, all of my player got kicked without no reason and there is an error from your plugin:
 - https://hastebin.com/inigizojam.css

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
https://hastebin.com/oweqebepah.http
```

**Comment by Htepple** [comment]
Same problem

**Comment by PetteriM1** [comment]
And which version is that since you didn't include the debugpaste? Config version tells that it's not the latest at least
