### ISSUE TITLE
/spawnmob command

### ISSUE THREAD

**Issue by snaildos** [Nukkit-coders/MobPlugin#138]
### Info

This is:
- [ ] bug report
- [ x] feature request
- [ ] other

### Your issue / suggestion
Please add a /spawnmob (mob TYPR) (amount of mobs to be spawned) 

This would help for spawning a lot of mobs with a certain amount.

**Comment by PetteriM1** [comment]
You can make your own command for that because it's not vanilla behavior and there is already two commands to spawn mobs
