### ISSUE TITLE
Zombies dont aggro

### ISSUE THREAD

**Issue by Valkrium** [Nukkit-coders/MobPlugin#139]
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
After Working on Bedrock server with Nukkit for a week, I noticed that the zombies and villager zombies dont aggro nor attack you when walking up to them.

**Comment by PetteriM1** [comment]
Unable to confirm. Feel free to create a new issue with more information if you think that this still exists.
