### ISSUE TITLE
Mobs not spwning and /mob spawn command does not work

### ISSUE THREAD

**Issue by thepilotvoltage** [Nukkit-coders/MobPlugin#141]
Mods are not spawning on my server and when I try to run the /spawn mob <mob> command it says "Unable to spawn Zombie"

Here are my plugins installed:

![Capture](https://user-images.githubusercontent.com/60161501/72852727-77fefe80-3c7d-11ea-9a7c-65ae56a4d70d.PNG)

**Comment by Htepple** [comment]
server.properties

**Comment by PetteriM1** [comment]
/mob spawn command uses entity names so it is case sensitive. You can also use /summon command.

**Comment by thepilotvoltage** [comment]
> server.properties

![Capture](https://user-images.githubusercontent.com/60161501/72885294-a01a4c00-3cd5-11ea-8e30-428213ad840d.PNG)
