### ISSUE TITLE
Mobs Not Dropping Items

### ISSUE THREAD

**Issue by SaintADW** [Nukkit-coders/MobPlugin#146]
I just installed the plugin to a GGServer, Nukkit Bedrock server. When killed, mobs are not dropping items.

**Comment by PetteriM1** [comment]
Sounds like the Nukkit version you are using is outdated. There is a reason why you should follow the issue template...

**Comment by SaintADW** [comment]
Quite rude, but thank you for the reply.

**Comment by PetteriM1** [comment]
> Quite rude, but thank you for the reply.

Sorry. Not meant to be rude. Just hoping that people would do some research and make sure they are on the latest versions before creating bug reports or at least include the information suggested in the issue template to the report. This way you don't make extra work for the developers.

**Comment by SaintADW** [comment]
---
name: New Issue
about: Bug
title: ''
labels: ''
assignees: ''

---

### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
Mobs are not dropping items.Best I can tell, I'm running the latest, public version of Nukkit.

### Configuration
Link to debugpaste:
https://hastebin.com/aziyepewiy

Config:
 config version, do not edit!

config-version: 11

entities:
   how often the spawn task should run
   in ticks, 20 ticks = 1 second
  use 0 to disable entity spawning
  autospawn-ticks: 200
   how often the despawn task should run
   in ticks, 20 ticks = 1 second
   use 0 to disable entity despawning
  despawn-ticks: 6000
   do not spawn entities in these worlds
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

 spawning limit settings
 per player, in 100 blocks range
autospawn:
  bat: 1
  blaze: 2
  chicken: 2
  cod: 2
  cow: 2
  creeper: 2
  dolphin: 1
  donkey: 1
  enderman: 1
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 1
  pig: 2
  polarbear: 2
  pufferfish: 1
  rabbit: 1
  salmon: 3
  sheep: 2
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 1
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 3

other:
   mob spawner spawning range
  spawner-spawn-range: 8
   don't reduce spawn eggs if there is same entity already in the spawner (non vanilla behavior)
  do-not-waste-spawn-eggs: false
   give xp drops straight to player
  use-no-xp-orbs: false
   do not spawn mobs this near to spawn area
  spawn-no-spawning-area: 1
   kill entities instead of despawning them
  kill-mobs-on-despawn: false

**Comment by PetteriM1** [comment]
1.11.2 is the latest version of MobPlugin but `git-1e49cad` is over month old Nukkit build which had this problem caused by a bad pull request. (See: https://github.com/NukkitX/Nukkit/issues/1136) Updating your Nukkit version should fix this issue.
