### ISSUE TITLE
[Bug] Creeper Mob AI

### ISSUE THREAD

**Issue by XKazzuKX** [Nukkit-coders/MobPlugin#154]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
When punching a creeper in creative mode after spawning one from a creeper egg, it will go in the direction you punched it for about 5 seconds.

https://youtu.be/OeCE3Ehcwnw

### Configuration
Link to debugpaste:
```
N/A
```
Config:
```
Default config.
```

**Comment by PetteriM1** [comment]
Seems to be fixed
