### ISSUE TITLE
spawning of mobs in the_end world

### ISSUE THREAD

**Issue by Mainek** [Nukkit-coders/MobPlugin#158]
make spawn mobs in the_end like in vanilla

**Comment by good777LUCKY** [comment]
In the_end world, it will spawn anyting like overworld. Can you make a the_end spawnrule things?

**Comment by good777LUCKY** [comment]
Maybe it is this question.

**Comment by Mainek** [comment]
![Screenshot_20200605_231014_com icecoldapps screenshoteasy](https://user-images.githubusercontent.com/59147402/83918680-e56d8080-a781-11ea-8cd7-69befa55c5ff.jpg)
