### ISSUE TITLE
Walking Entities sometime flying (High Jump)

### ISSUE THREAD

**Issue by good777LUCKY** [Nukkit-coders/MobPlugin#159]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

Walking entities sometime flying(very high jump).

### Configuration
Link to debugpaste:
```
-
```
Config:
```
(Default Config)
```

**Comment by PetteriM1** [comment]
Still happening in version 1.12.0?

**Comment by good777LUCKY** [comment]
I will check again

**Comment by PetteriM1** [comment]
Unable to confirm
