### ISSUE TITLE
Fireball is look like xp orb

### ISSUE THREAD

**Issue by GoodLucky777** [Nukkit-coders/MobPlugin#165]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

When you see fireball you can see glowing thing like xp orb. (yellow green color)
### Configuration
Link to debugpaste:
```
-
```
Config:
```
(default config)
```

**Comment by PetteriM1** [comment]
Fixed in https://github.com/Nukkit-coders/MobPlugin/commit/a20536327580a1727752f085ae759a61e730e772
