### ISSUE TITLE
Some buggy entity go to 0, ?, 0 coordinate

### ISSUE THREAD

**Issue by GoodLucky777** [Nukkit-coders/MobPlugin#166]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

When buggy entity like #151 created, it goes to 0, ?, 0 and when mobile player go there it will crash too.

### Configuration
Link to debugpaste:
```
-
```
Config:
```
(default config)
```

**Comment by good777LUCKY** [comment]
I don't know why but when I remove all mobs when I go there (crashing zone), it will fixed.
