### ISSUE TITLE
Another Creeper AI Bug

### ISSUE THREAD

**Issue by good777LUCKY** [Nukkit-coders/MobPlugin#181]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

When Creeper striked by lightning bolt, Creeper will run about 8 seconds until fall or hit by block.
### Configuration
Link to debugpaste:
```
-
```
Config:
```
(default config)
```

### Related Issue
#154

**Comment by PetteriM1** [comment]
Seems to be fixed
