### ISSUE TITLE
Mob Plugin doesn't work on CustomWorlds

### ISSUE THREAD

**Issue by Lusmft** [Nukkit-coders/MobPlugin#184]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
I downloaded a custom terrain map "Epic Fantasy Map" on Nukkit server and there is mobs don't autospawn at all! But I can spawn them from egg and they are walking ok.

**Comment by PetteriM1** [comment]
Can you please send your config and other info requested in the issue template

**Comment by Lusmft** [comment]
Sorry, I've change map :D
