### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by ipad54** [Nukkit-coders/MobPlugin#185]
### Info

This is:
- [ ] bug report
- [X ] feature request
- [ ] other

### Your issue / suggestion

Please, make sure that the wither can break obsidian

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by Htepple** [comment]
He can't #104

**Comment by PetteriM1** [comment]
Duplicate of #104
