### ISSUE TITLE
Can you add entity class for human?

### ISSUE THREAD

**Issue by qPexLegendary** [Nukkit-coders/MobPlugin#189]
### Info

This is:
- [ ] bug report
- [X] feature request
- [ ] other

### Your issue / suggestion
Can you make entity class for human? Just I want make custom mob(human with skin and model) but I cant because I dont know how do it :/ And your plugin already has AI and it will make work easier in the future.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
This is not something what will be added into this plugin
