### ISSUE TITLE
Spawner doesn't work

### ISSUE THREAD

**Issue by Jl1mbo** [Nukkit-coders/MobPlugin#210]
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
When I click on the spawn, the mob that I want to shove is simply not put there, and it just spawns next to it, as if the spawners are disabled

### Configuration
Link to debugpaste:
```
never
```
Config:
```
don't change
```

**Comment by PetteriM1** [comment]
Please provide the config and debugpaste link

**Comment by Jl1mbo** [comment]
> Please provide the config and debugpaste link

config - https://hastebin.com/munihutipi.yaml (default)

debug - https://hastebin.com/usatojaviw

**Comment by PetteriM1** [comment]
Unofficial Nukkit versions are not supported

**Comment by Jl1mbo** [comment]
Could you support the latest version?

**Comment by PetteriM1** [comment]
> Could you support the latest version?

I do support the latest version - on NukkitX
