### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by YazdanPlug** [Nukkit-coders/MobPlugin#212]
The mobs sink to the ground and do not move well. You can not trade with the villagers. It is not possible to ride a horse or a donkey. Wolfs and cats cannot be domesticated. please fix these problems.

**Comment by Jl1mbo** [comment]
A little bit of everything

**Comment by PetteriM1** [comment]
One issue per report please so I can use these to track the progress of bugs getting fixed

Mobs going inside ground is something that started after the 1.16.100 update

**Comment by PetteriM1** [comment]
Duplicate of #207
