### ISSUE TITLE
Mobs dont spawn in snowy tundra

### ISSUE THREAD

**Issue by dani31c** [Nukkit-coders/MobPlugin#214]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

Well, the mobs dont spawn in snowy tundras, seamingly. Using the latest version of Nukkit for 1.16.2 MCPE and latest version of the mod (1.17.2)

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Duplicate of #192
