### ISSUE TITLE
Add ArmorStand

### ISSUE THREAD

**Issue by riesters** [Nukkit-coders/MobPlugin#218]
### Info

This is:
- [ ] bug report
- [X] feature request
- [ ] other

### Your issue / suggestion
please make armorstand spawnable

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by Jl1mbo** [comment]
lol, this is not an Entity with AI

**Comment by riesters** [comment]
> lol, this is not an Entity with AI

True, but why make it its own plugin?

**Comment by Jl1mbo** [comment]
> > lol, this is not an Entity with AI
> 
> True, but why make it its own plugin?

This must be done in the core.
