### ISSUE TITLE
pointers to how to use this would be helpful

### ISSUE THREAD

**Issue by petercwallis** [Nukkit-coders/MobPlugin#219]
### Info

This is:
- [ ] bug report
- [X] feature request
- [ ] other

### Your issue / suggestion
I am trying to find out how to modify a mob behaviour.  I'm 'expert' java user, and can have found this tutorial from the bukkit site:
 https://bukkit.org/threads/tutorial-how-to-customize-the-behaviour-of-a-mob-or-entity.54547/
Is there a more relevant tutorial for this MobPlugin?
Also the bukkit tutorial says how to write the code but not where to put it :-/

**Comment by PetteriM1** [comment]
Bukkit tutorials about entities won't probably help much on Nukkit. If you want to customize mob behavior you need to create an entity class that extends the correct entity class from Nukkit or MobPlugin and then register it using `Entity.registerEntity`. Unfortunately there isn't much documentation of anything on Nukkit so the best place to look for help is other plugins (including this one). With lack of documentation of this plugin I will refer to #220.
