### ISSUE TITLE
Cow Bug/Only Collect Milk with Creative Buckets

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#223]
### Info

This is:
- [ x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

You can only collect Milk from Cows with Gamemode Creative Buckets. 
Gamemode Survival Buckets disapears. 

Mob Plugin 1.19.0

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Fixed in 961ae6d
