### ISSUE TITLE
Mob Loot

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#224]
### Info

This is:
- [x  bug report
- [ ] feature request
- [x] other

### Your issue / suggestion
 If a mob spawns in a wall and dies, you can collect the dropped items. 
I dont know its a Nukkit Bug or a Bug by MobPlugin

MobPlugin 1.19.0

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by MonoAdrian23** [comment]
![IMG_20210524_132429.jpg](https://user-images.githubusercontent.com/59027482/119341615-4a243280-bc94-11eb-913d-dbe36e414260.jpg)

**Comment by Jl1mbo** [comment]
And what is the actual problem?  Mob died, things fell from him, everything is correct.  And the fact that the mob spawned in the wall is the problem with this plug

**Comment by PetteriM1** [comment]
Vanilla behaviour. (not spawning into walls but getting the drops of a suffocated mob)
