### ISSUE TITLE
Baby Chickens / Texture Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#226]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
 When a chicken hatches from an egg, it gets this texture

I use MobPlugin 1.19.0

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Gets what texture? Please include debugpaste and steps to reproduce the issue.

**Comment by MonoAdrian23** [comment]
Oh man, my picture was failed to Upload.
I Hope i can send a New one.
The chickens head was the chicken without hitbox.
