### ISSUE TITLE
Mob dont make baby

### ISSUE THREAD

**Issue by Doxestic** [Nukkit-coders/MobPlugin#237]
### Info

This is:
- [X] bug report
- [x] feature request
- [ ] other

### Your issue / suggestion

When feed 2 cow or chiken or other mobs they dont try to make baby
Using last version of mob plugin
### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Not implemented yet. Duplicate of #100
