### ISSUE TITLE
Cant find any Slimes in Nukkits World

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#244]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
 I cant find any Slimes in Nukkits Normal Generator.
In BetterVanillaGenerator, Slimes Spawn.
I have never Seen a slime in normal World.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PocketMiner92** [comment]
You can Close this.
It workes fine, i have tested it
