### ISSUE TITLE
Some horses spawn with saddles

### ISSUE THREAD

**Issue by Vojvas** [Nukkit-coders/MobPlugin#247]
We have PowerNukkit server and my friends told me there are horses with saddles in savanna. So I go to the spectator and yeah, it is true. Before it, one of friends put saddle on horse and another killed him (horse). After, horses is spawning much more with saddles.
This is:
- [ X] bug report
- [ ] feature request
- [ ] other

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by MonoAdrian23** [comment]
Powernukkit isnt Supported!

**Comment by PetteriM1** [comment]
Please only report issues you can reproduce on the official Nukkit.
