### ISSUE TITLE
Breeding

### ISSUE THREAD

**Issue by Vojvas** [Nukkit-coders/MobPlugin#248]
Hello, I find a very weird bug: you can't breed mobs like cow etc. and yeah, it is so bad. Please add it on nukkit.

This is:
- [ ] bug report
- [X ] feature request
- [ ] other

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Duplicate of #100
