### ISSUE TITLE
Polar Bear Spawn randomly in Caves

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#249]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
 Polar Bear Spawn Randomly in Caves.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Duplicate of #78
