### ISSUE TITLE
Bug with Nametags

### ISSUE THREAD

**Issue by PocketMiner92** [Nukkit-coders/MobPlugin#252]
### Info

This is:
- [x] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

Rename a Stack Nametags
Tame a Mob
Give this Mob a Nametag
All Nametags dissapear and the Mob is renamed.
In Vanilla, only one Nametag is used from the stack.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Fixed in https://github.com/CloudburstMC/Nukkit/pull/1950
