### ISSUE TITLE
Missing Drop for Wither Skeleton

### ISSUE THREAD

**Issue by PocketMiner92** [Nukkit-coders/MobPlugin#260]
### Info

This is:
- [ ] bug report
- [x] feature request
- [ ] other

### Your issue / suggestion
 In Vanilla, Wither Skeleton should Drop Bones, Coal and Stone Sword.
The Stone Sword is Missing in Drops.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
The drop exists in the code
https://github.com/Nukkit-coders/MobPlugin/blob/875ff4b35f7c35971902b883093f314c18da16c8/src/main/java/nukkitcoders/mobplugin/entities/monster/walking/WitherSkeleton.java#L107-L109

**Comment by PocketMiner92** [comment]
But it doenst Drop a Sword.

**Comment by PocketMiner92** [comment]
Sorry
After 50 Kills it works.
But why is this so rare?
