### ISSUE TITLE
Feature Request (Allay)

### ISSUE THREAD

**Issue by MonoAdrian23** [Nukkit-coders/MobPlugin#263]
### Info

This is:
- [ ] bug report
- [x] feature request
- [ ] other

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
Added in https://github.com/Nukkit-coders/MobPlugin/commit/488fa565b34bfb94018bba6117d5897e5fdc22a8 / version 1.22.0
