### ISSUE TITLE
Mobs Despawn Quickly

### ISSUE THREAD

**Issue by silas0526** [Nukkit-coders/MobPlugin#265]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion

I try to make mob farms but the animals despawn before i can do anything!

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Config:
```
<!-- Put your config.yml contents here  -->
```

**Comment by PetteriM1** [comment]
You can increase the time mobs stay before despawning by changing `entities.despawn-ticks`  in config.yml. Default is 6000 (5 minutes) and setting a value <= 0 disables despawning completely.

**Comment by silas0526** [comment]
Is the file in a directory? I don't see the file. I do see nukkit.yml, though. I looked at it and saw nothing.
