### ISSUE TITLE
PowerNukkitX crashes on login with V1.22.1

### ISSUE THREAD

**Issue by f465gt** [Nukkit-coders/MobPlugin#266]
### Info

This is:
- [X] bug report
- [ ] feature request
- [ ] other

### Your issue / suggestion
I am running a PowerNukkitX server (yes I know, it is a fork) that completely stops at login when using the V1.22.1 of the MobPlugin. With V1.22.0 everything is fine.
I attached the logfile: https://hastebin.com/zicematane.sql
So the server starts, but as soon as a player logs in, it shuts down.

### Configuration
Link to debugpaste:
```
<!-- Run debugpaste command and put the link here -->
```
Sorry, I can't execute this command.
```
config.yml is default as set by your jar file.

```

**Comment by PetteriM1** [comment]
Looks like this Nukkit version is outdated (doesn't support the new server authoritative movement system). Anyway, support is provided only for the official Cloudburst Nukkit here.

**Comment by f465gt** [comment]
Thanks for the quick reply. That's very interesting. The PNX server is running V1.19.20. So I will wait for updates.
Thanks again for your effort!
