### ISSUE TITLE
Some Kind Of Error

### ISSUE THREAD

**Issue by kimbunner** [Nukkit-coders/MobPlugin#275]
### Info

This is:
- [X ] bug report
- [ ] feature request
- [ ] other

Screenshot:
``https://firebasestorage.googleapis.com/v0/b/edith-server-01.appspot.com/o/Screenshot%202023-01-07%20142908.png?alt=media&token=bc4b5aae-42c5-4df6-b2e0-8d7a48803a00``

Debugpaste:
``https://firebasestorage.googleapis.com/v0/b/edith-server-01.appspot.com/o/debugpaste-2023-01-07T14.26.57.986%2B0800.zip?alt=media&token=f167a366-7b3e-4b41-8baa-4e7003acaf41``

**Comment by PetteriM1** [comment]
Use latest Nukkit version
