### ISSUE TITLE
MobPlugin Cannot Be Moved To "plugins" Folder

### ISSUE THREAD

**Issue by Rubinoid** [Nukkit-coders/MobPlugin#281]
I am unable to install the plugin because my computer doesn't allow any changes to the "plugins" folder. In terminal I get "No such file or directory" when running
sudo mv MobPlugin-1.25.2.jar plugins
and in the File Manger, I get "Permission Denied" when manually moving the plugin. What can I do to fix this?

**Comment by DiegoS-E** [comment]
Nvm, I figured it out

**Comment by Rubinoid** [comment]
Nvm, I figured it out
