### ISSUE TITLE
Fireballs break cobblestone

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/MobPlugin#31]
Ghasts and blazes can break cobblestone

**Comment by PetteriM1** [comment]
Blazes too

**Comment by PikyCZ** [comment]
Ghast and Blazes still can break cobblestone

**Comment by NycuRO** [comment]
ok. Need check tommorow

**Comment by NycuRO** [comment]
But bug was by FireBall, not by ghast. When ghast shut, he spawn a fireball.
Them break blocks.

**Comment by PikyCZ** [comment]
I know NycuRo

**Comment by PikyCZ** [comment]
I know NycuRo
