### ISSUE TITLE
Path finder is broken

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/MobPlugin#72]
@zzz1999 Please read this and fix problems as fast as possible or I need to remove your path finder from this plugin.

So..
1. Skeletons, endermans, spiders etc. don't change their path even to attack
2. Sometimes when you hit mobs they start to move backward or sideways
3. Skeletons always shoot just ahead
4. If zombie see you once it folows you very far
5. Animals don't respond to food
6. Some mobs and animals can't jump (example creeper)
7. Spiders can't float on water

**Comment by zzz1999** [comment]
Sorry,I have no time recently.
Maybe next month I will have time fix it,approximate..
By the way,why this issue are "high priority",I never know any issue is high priority before.

**Comment by PetteriM1** [comment]
And also #70 is path finder bug but fixing it isn't high priority

**Comment by zzz1999** [comment]
Level#getEntities() is not including Player now?

**Comment by PetteriM1** [comment]
@zzz1999 If you have some time please try to fix at least monsters targeting

**Comment by zzz1999** [comment]
@PetteriM1 I'll try my  best,if i have free time and computer
