### ISSUE TITLE
Cant Tame or Saddle Horses

### ISSUE THREAD

**Issue by rcr682k2** [Nukkit-coders/MobPlugin#77]
### Issue Description
Cant tame or saddle horses
Write a short description about the issue
cant tame or saddle horses
### Steps to Reproduce the Issue

1. ...
2. ...
3. ...

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
```

Put config here

```
### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by PetteriM1** [comment]
This feature is not implemented yet
