### ISSUE TITLE
Mobs burn in night

### ISSUE THREAD

**Issue by EnterTG** [Nukkit-coders/MobPlugin#79]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. Some time mobs spawned in night are burning.

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
```

Default

```
### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by PetteriM1** [comment]
How often is your "some time"? How much minecraft time was then? What mobs spawned burning?
Btw your config cannot be default because default config spawn only animals

**Comment by EnterTG** [comment]
- Burning mob: Zombie(Even with a hat)
- Time such that the mobs should not be burning. Time set with the command / time set night
- Config default, I spawn mobs with my own plugin
- How often some time, i don't see a pattern

**Comment by PetteriM1** [comment]
Time values for mob burning are from Minecraft wiki and they should be right but seems that values for /time command in Nukkit are wrong.
