### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Cobwebster** [Nukkit-coders/MobPlugin#86]
I upped spawn rates to 50 on most mobs, is it normal for spawn eggs not to work?

**Comment by PetteriM1** [comment]
Setting spawn rates high causes much server load. You shoul instead change how often spawner runs. (autospawn ticks) And last time I tested spawn eggs worked so idk.

**Comment by PetteriM1** [comment]
Just tested and spawn eggs work. Idk why them dont work for you.

**Comment by Cobwebster** [comment]
Issue was on my end, resolved :)
