### ISSUE TITLE
suicidal mobs

### ISSUE THREAD

**Issue by Cobwebster** [Nukkit-coders/MobPlugin#87]
Hey,

Any chance mobs can path find a little better? On skyblock they just spawn and instantly walk off the island. anyway to stop them falling like that?

**Comment by hpux735** [comment]
This sounds like a similar bug to what I'm seeing; that is that livestock animals don't respect fencing.  I believe there's a missing check in updateMove for WalkingEntity https://github.com/Nukkit-coders/MobPlugin/blob/master/src/main/java/nukkitcoders/mobplugin/entities/WalkingEntity.java#L130 

I'm happy to look into this bug, but I'll happily accept any pointers or advice.

**Comment by hpux735** [comment]
Could it be this line?  I'm not sure I understand the gravity stuff, but it seems like if it's a fence it shouldn't be allowed to jump?

https://github.com/Nukkit-coders/MobPlugin/blob/master/src/main/java/nukkitcoders/mobplugin/entities/WalkingEntity.java#L115

**Comment by TheIronMinerLv** [comment]
Bump, that running off cliffs (so running of islands) and ignoring fences and cobble walls is an issue @PetteriM1 could you look into this? Thanks.

**Comment by PetteriM1** [comment]
> Bump, that running off cliffs (so running of islands) and ignoring fences and cobble walls is an issue @PetteriM1 could you look into this? Thanks.

That is because the current AI is not real AI. It just makes mobs and animas move randomly around but doesn't make them "smart". Implementing real vanilla like AI will be big project and it will be hopefully included in Nukkit rewrite.
