### ISSUE TITLE
Mob issues

### ISSUE THREAD

**Issue by whoatemycookie8297** [Nukkit-coders/MobPlugin#97]
Rabbits run in place, skeletons have no shooting animation, animals have extra health for some reason. Endermen don't react to water, this is with the latest nukkitx and mobplugin

**Comment by PetteriM1** [comment]
Endermans should react to water...

**Comment by whoatemycookie8297** [comment]
Zombies like walk @ player speed

**Comment by whoatemycookie8297** [comment]
Endermen take damage from water but it doesn't tp them to land just further in water.

**Comment by PetteriM1** [comment]
Extra health bug is fixed in the latest version

**Comment by ZizzyZizzy** [comment]
Add "mobs randomly tread water and lava" to this list. Spiders, wolfs, etc. will just walk into water and lava as if they were solid blocks. They should avoid by default.

**Comment by Guns29** [comment]
hell animals spawn but dumb as shit when in skyblock they just jump of the cliff and die hahaha as monsters they dont spawn at all not sure whats going on
